/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as InsightRouteImport } from './routes/insight'
import { Route as MoreRouteImport } from './routes/more'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as MoreIndexRouteImport } from './routes/more.index'
import { Route as MoreSectionRouteImport } from './routes/more.$section'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsCashFlowRouteImport } from './routes/reports.cash-flow'
import { Route as ReportsProfitLossRouteImport } from './routes/reports.profit-loss'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightRoute = InsightRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MoreIndexRoute = MoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MoreRoute,
} as any)
const MoreSectionRoute = MoreSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => MoreRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsCashFlowRoute = ReportsCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsProfitLossRoute = ReportsProfitLossRouteImport.update({
  id: '/profit-loss',
  path: '/profit-loss',
  getParentRoute: () => ReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRoute
  '/insight': typeof InsightRoute
  '/more': typeof MoreRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/welcome': typeof WelcomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/more/$section': typeof MoreSectionRoute
  '/reports/cash-flow': typeof ReportsCashFlowRoute
  '/reports/profit-loss': typeof ReportsProfitLossRoute
  '/more/': typeof MoreIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRoute
  '/insight': typeof InsightRoute
  '/onboarding': typeof OnboardingRoute
  '/transactions': typeof TransactionsRoute
  '/welcome': typeof WelcomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/more/$section': typeof MoreSectionRoute
  '/reports/cash-flow': typeof ReportsCashFlowRoute
  '/reports/profit-loss': typeof ReportsProfitLossRoute
  '/more': typeof MoreIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRoute
  '/insight': typeof InsightRoute
  '/more': typeof MoreRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/more/$section': typeof MoreSectionRoute
  '/reports/cash-flow': typeof ReportsCashFlowRoute
  '/reports/profit-loss': typeof ReportsProfitLossRoute
  '/more/': typeof MoreIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/businesses'
    | '/insight'
    | '/more'
    | '/onboarding'
    | '/reports'
    | '/transactions'
    | '/welcome'
    | '/profile'
    | '/more/$section'
    | '/reports/cash-flow'
    | '/reports/profit-loss'
    | '/more/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/businesses'
    | '/insight'
    | '/onboarding'
    | '/transactions'
    | '/welcome'
    | '/profile'
    | '/more/$section'
    | '/reports/cash-flow'
    | '/reports/profit-loss'
    | '/more'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/businesses'
    | '/insight'
    | '/more'
    | '/onboarding'
    | '/reports'
    | '/transactions'
    | '/welcome'
    | '/_authenticated/profile'
    | '/more/$section'
    | '/reports/cash-flow'
    | '/reports/profit-loss'
    | '/more/'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BusinessesRoute: typeof BusinessesRoute
  InsightRoute: typeof InsightRoute
  MoreRoute: typeof MoreRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  TransactionsRoute: typeof TransactionsRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight': {
      id: '/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof InsightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/more/': {
      id: '/more/'
      path: '/'
      fullPath: '/more/'
      preLoaderRoute: typeof MoreIndexRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/$section': {
      id: '/more/$section'
      path: '/$section'
      fullPath: '/more/$section'
      preLoaderRoute: typeof MoreSectionRouteImport
      parentRoute: typeof MoreRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/cash-flow': {
      id: '/reports/cash-flow'
      path: '/cash-flow'
      fullPath: '/reports/cash-flow'
      preLoaderRoute: typeof ReportsCashFlowRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/profit-loss': {
      id: '/reports/profit-loss'
      path: '/profit-loss'
      fullPath: '/reports/profit-loss'
      preLoaderRoute: typeof ReportsProfitLossRouteImport
      parentRoute: typeof ReportsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MoreRouteChildren {
  MoreSectionRoute: typeof MoreSectionRoute
  MoreIndexRoute: typeof MoreIndexRoute
}

const MoreRouteChildren: MoreRouteChildren = {
  MoreSectionRoute: MoreSectionRoute,
  MoreIndexRoute: MoreIndexRoute,
}

const MoreRouteWithChildren = MoreRoute._addFileChildren(MoreRouteChildren)

interface ReportsRouteChildren {
  ReportsCashFlowRoute: typeof ReportsCashFlowRoute
  ReportsProfitLossRoute: typeof ReportsProfitLossRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsCashFlowRoute: ReportsCashFlowRoute,
  ReportsProfitLossRoute: ReportsProfitLossRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BusinessesRoute: BusinessesRoute,
  InsightRoute: InsightRoute,
  MoreRoute: MoreRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ReportsRoute: ReportsRouteWithChildren,
  TransactionsRoute: TransactionsRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
