/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as InsightRouteImport } from './routes/insight'
import { Route as MoreRouteImport } from './routes/more'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsCashFlowRouteImport } from './routes/reports.cash-flow'
import { Route as ReportsProfitLossRouteImport } from './routes/reports.profit-loss'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightRoute = InsightRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsCashFlowRoute = ReportsCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsProfitLossRoute = ReportsProfitLossRouteImport.update({
  id: '/profit-loss',
  path: '/profit-loss',
  getParentRoute: () => ReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/businesses': typeof BusinessesRoute
  '/insight': typeof InsightRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/reports/cash-flow': typeof ReportsCashFlowRoute
  '/reports/profit-loss': typeof ReportsProfitLossRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/businesses': typeof BusinessesRoute
  '/insight': typeof InsightRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/transactions': typeof TransactionsRoute
  '/reports/cash-flow': typeof ReportsCashFlowRoute
  '/reports/profit-loss': typeof ReportsProfitLossRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/businesses': typeof BusinessesRoute
  '/insight': typeof InsightRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/reports/cash-flow': typeof ReportsCashFlowRoute
  '/reports/profit-loss': typeof ReportsProfitLossRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/businesses'
    | '/insight'
    | '/more'
    | '/onboarding'
    | '/reports'
    | '/transactions'
    | '/reports/cash-flow'
    | '/reports/profit-loss'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/businesses'
    | '/insight'
    | '/more'
    | '/onboarding'
    | '/transactions'
    | '/reports/cash-flow'
    | '/reports/profit-loss'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/businesses'
    | '/insight'
    | '/more'
    | '/onboarding'
    | '/reports'
    | '/transactions'
    | '/reports/cash-flow'
    | '/reports/profit-loss'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessesRoute: typeof BusinessesRoute
  InsightRoute: typeof InsightRoute
  MoreRoute: typeof MoreRoute
  OnboardingRoute: typeof OnboardingRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight': {
      id: '/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof InsightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/cash-flow': {
      id: '/reports/cash-flow'
      path: '/cash-flow'
      fullPath: '/reports/cash-flow'
      preLoaderRoute: typeof ReportsCashFlowRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/profit-loss': {
      id: '/reports/profit-loss'
      path: '/profit-loss'
      fullPath: '/reports/profit-loss'
      preLoaderRoute: typeof ReportsProfitLossRouteImport
      parentRoute: typeof ReportsRoute
    }
  }
}

interface ReportsRouteChildren {
  ReportsCashFlowRoute: typeof ReportsCashFlowRoute
  ReportsProfitLossRoute: typeof ReportsProfitLossRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsCashFlowRoute: ReportsCashFlowRoute,
  ReportsProfitLossRoute: ReportsProfitLossRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessesRoute: BusinessesRoute,
  InsightRoute: InsightRoute,
  MoreRoute: MoreRoute,
  OnboardingRoute: OnboardingRoute,
  ReportsRoute: ReportsRouteWithChildren,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
